### ISSUE TITLE
Dev module re-defines the 5 ProprertyDesc of kernel without Module property

### ISSUE THREAD

**Issue by kovax** [cristal-ise/dev#6]
The dev module redefines these 5 resources of kernel:

CAProp.xml
EAProp.xml
ODProp.xml
SCProp.xml
SMProp.xml

All theses are very similar to the kernel verzion but none of the contains them Module property. Is this a bug or a feature?

**Comment by abranson** [comment]
Don't worry about that, it's fine.

**Comment by kovax** [comment]
It would be great if you could explain a bit more details. Not urgent, just for the sake of documentation :)

**Comment by abranson** [comment]
I don't think this is the right place for such trivia: things that don't really affect anything, will be lost in the closed issues, and generate noise around actual fixes and features and fixes. I think we've got a few too many speculative future work issues too.
